dictonary/dictonary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
]

dictonary/main/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, words_list, add_word

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('home/', index, name='home'),
    path('words_list/', words_list, name='words_list'),
    path('add_word/', add_word, name='add_word'),
]

dictonary/main/models.py
from django.db import models

# Create your models here.

dictonary/main/forms.py
from django import forms


class WordForm(forms.Form):
    word = forms.CharField(max_length=50)
    p = forms.CharField(max_length=50)

dictonary/main/views.py
from django.shortcuts import render
import pandas as pd
import csv
from .forms import WordForm

# Create your views here.


def index(request):
    # df = pd.DataFrame({'Слово': [], 'Перевод': []})
    # df.to_csv('table.csv')
    context = {'title': 'Домашняя страница'}
    return render(request, 'main/index.html', context)


def words_list(request):
    with open('table.csv', 'r', encoding='utf-8') as file:
        table = csv.reader(file)
        m = []
        for i in table:
            m.append((i[1], i[2]))
        context = {'title': 'Список слов',
                   'table': m}
    return render(request, 'main/words_list.html', context)


def add_word(request):
    error = ''
    if request.method == 'POST':
        form = WordForm(data=request.POST)
        if form.is_valid():
            word = form.cleaned_data.get('word')
            p = form.cleaned_data.get('p')
            table = pd.read_csv('table.csv', encoding='utf-8')
            table.loc[len(table.index)] = [len(table.index), word, p]
            table.to_csv('table.csv')
    else:
        form = WordForm()

    context = {'title': 'Добавить запись',
               'form': form
               }
    return render(request, 'main/add_word.html', context)

dictonary/main/templates/main/add_word.html
{% extends 'main/base.html'%}

{% block css %}
{% endblock %}

{% block content %}
<form action="{% url 'main:add_word' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Составить</button>
    <a href="{% url 'main:words_list' %}" class="btn">Выйти</a>
</form>
{% endblock %}

dictonary/main/templates/main/base.html
<!DOCTYPE html>

<html lang="ru">
<head>
    <title>{{ title }}</title>
    <style>
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #FFFFFF;
        }

        .card {
            background-color: #808080;
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            transition: 0.3s;
            border-radius: 5px;
            padding: 50px 20px;
        }

        .btn {
            background-color: #FFFFFF;
            color: black;
            padding: 10px 20px;
            border: none;
            text-decoration: none;
            border-radius: 5px;
            cursor: pointer;
            margin: 10px;
            }

        button {
            background-color: #FFFFFF;
            color: black;
            padding: 10px 20px;
            border: none;
            text-decoration: none;
            border-radius: 5px;
            cursor: pointer;
            margin: 10px;
        }
        table {
            margin-top: 10px;
            margin-right: 5px;
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            padding: 10px;
            text-align: left;
            border: 1px solid #FFFFFF;
            background-color: #FFFFFF;
        }

        input[type=text], textarea {
            background-color: #FFFFFF;
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        select {
            margin: 8px;
            padding: 8px 16px;
        }
        {% block css %}
        {% endblock %}
    </style>
</head>
<body style="background-color: #FFFFFF">
 <div class="container">
        <div class="card">
            {% block content%} {% endblock %}
        </div>
    </div>
</body>
</html>

dictonary/main/templates/main/index.html
{% extends 'main/base.html'%}

{% block css %}
.title {
    background-color: #FFFFFF;
    color: black;
    padding: 10px 20px;
    border: none;
    text-decoration: none;
    cursor: pointer;
    border-radius: 3px;
    }
.description {
    background-color: #FFFFFF;
    color: black;
    padding: 10px 20px;
    border: none;
    text-decoration: none;
    cursor: pointer;
    border-radius: 3px;
    }
{% endblock %}

{% block content %}
<div>
    <h4 class="title">Словарь иностранных слов</h4>
    <p class="description">
        На сайте есть возможность просматривать список иностранных слов с переводом
        и добавлять новые.
    </p>
</div>
<div>
    <a href="{% url 'main:words_list' %}" class="btn">Список слов</a>
</div>
{% endblock %}

dictonary/main/templates/main/words_list.html
{% extends 'main/base.html'%}

{% block css %}
.words_list_body {
	height: 200px;
	overflow-x: auto;
	margin-top: 0px;
	margin-bottom:30px;
	border-bottom: 1px solid #eee;
}
.words_list table {
	width:100%;
	table-layout: auto;
	border: none;
}
.words_list thead th {
	font-weight: bold;
	text-align: left;
	border: none;
	padding: 10px 15px;
	background: #d8d8d8;
	font-size: 14px;
	border-left: 1px solid #ddd;
	border-right: 1px solid #ddd;
}
.words_list tbody td {
	text-align: left;
	border-left: 1px solid #ddd;
	border-right: 1px solid #ddd;
	padding: 10px 50px;
	font-size: 14px;
	vertical-align: top;
}
.words_list_body tbody tr:nth-child(even){
	background: #f3f3f3;
}

/* Стили для скролла */
::-webkit-scrollbar {
	width: 6px;
}
::-webkit-scrollbar-track {
	box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}
::-webkit-scrollbar-thumb {
	box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}
{% endblock %}

{% block content %}
<div class="words_list">
    <table id="words_table">
        <thead>
        <tr>
            <th>Слово</th>
            <th>Перевод</th>
        </tr>
        </thead>
    </table>
    <div class="words_list_body">
        <table>
            <tbody>
            {% for w, p in table %}
            <tr>
                <td>{{ w }}</td>
                <td>{{ p }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<p>
	<a href="{% url 'main:add_word' %}" class="btn">Добавить слово</a>
</p>
{% endblock %}